services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: postgres
    volumes:
      - psql_volume:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - default
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_KEY=${JWT_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - default
networks:
  default:
volumes:
  psql_volume:
